config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'sites#index'

  resources :sites

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :site

end

app/models/site.rb
class Site < ActiveRecord::Base

	validates :url, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
 
  def create
  	site = Site.find_by(url: request.env['HTTP_ORIGIN'])
   	render json: "Unregistered application", status: :unprocessable_entity
  end

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

	def index
		@sites = Site.all
	end

	def new
		@site = Site.new
	end

	def create
		@site = Site.new(site_params)

		if @site.save
			flash[:notice] = "Site saved"
			redirect_to root_path
		else
			flash[:error] = "There was an error. Please try again"
			redirect_to new_site_path
		end
	end

	private

	def site_params
		params.require(:site).permit(:name, :url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<% if current_user %>
		<div class="welcome">
      Welcome <%= current_user.name %>!
			<%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
    </div>
	<% else %>
		<%= link_to 'Log in', new_user_session_path %>
		<%= link_to 'Sign up', new_user_registration_path %>
	<% end %>
</header>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% elsif flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/sites/index.html.erb
<%= link_to 'Add site', new_site_path %>

<div class="site-index">
	<%= @sites.each do |site| %>
		<%= link_to site.name, site_path(site.id) %>
	<% end %>
</div>

app/views/sites/new.html.erb
<%= form_for @site do |f| %>
	<span class="url_name">
		<%= f.label :Name %>
		<%= f.text_field :name %>
	</span>
	<%= f.label :url %>
	<%= f.text_field :url %>
	<%= f.submit "Add site" %>
<% end %>

app/views/sites/show.html.erb
<h1><%= @site.name %></h1>
<h2><%= @site.url %></h2>

<%= @siteevents.each do |s| %>
	<%= s.name %>
<% end %>

<%= @siteevents.count %>